# Change these first
owner: wexlerai # Your GitHub organization or username, where this repository lives
repo: wexler-client-status # The name of this repository

sites:
  - name: Application
    url: https://app.wexler.ai/
    expectedStatusCodes:
      - 403 # Meaning we were redirected to propel auth
      - 200 

  - name: API
    url: https://api.wexler.ai/
    
assignees: # Users to assign downtime issues (optional)
  - luisenriquecgongora
  - kushmadlani

status-website:
  baseUrl: /wexler-client-status # where "repo" is your repository name
  name: wexler.ai
  logoUrl: https://wexler.ai/favicon_png.png
  introTitle: "**Wexler** powered technology establishes the facts in any contentious matter."
  introMessage: Check here for incidents and the status of Wexler's APIs and services
  navbar:
    - title: Status
      href: /
